import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/theme-swticher";
import { I18nProvider } from "@/components/i18n-provider";
import { Toaster } from "@/components/ui/sonner";
import "@/i18n";
import "./globals.css";

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inconsolata.variable} antialiased`}
        style={{ margin: 0, padding: 0 }}
      >
        <I18nProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            <div className="absolute right-4 top-4 z-10">
              <ModeToggle />
            </div>
            {children}
            <Toaster />
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
